apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80              # Port exposed by the service
      targetPort: 5000      # Port your Flask app listens to inside the container
  type: LoadBalancer         # This will simulate an external LoadBalancer in Minikube


