apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80             # The port that the service will expose
      targetPort: 5000      # The port where your Flask app is running inside the container
      nodePort: 30001       # Port on the node (ensure it's in the valid NodePort range, e.g., 30000-32767)
  type: NodePort

